name: get links from gotify

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'

jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run grab --if-present
        env:
          GOTIFY_URL: ${{ secrets.GOTIFY_URL }}
          GOTIFY_TOKEN: ${{ secrets.GOTIFY_TOKEN }}
      - name: Commit and push if it changed
        run: |-
          git config user.name "Link Graber"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "[LINKS]: ${timestamp}" || exit 0
          git push