name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY_WO_PASSPHRASE }}
          source: "public"
          target: ${{ secrets.SSH_DIR }}
          rm: true
          strip_components: 1