name: schedule articles for syndication

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  schedule_articles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run schedule --if-present
      - name: Commit and push if there were changes
        run: |-
          git config user.name "Post Scheduler"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "[SCHEDULER]: ${timestamp}" || exit 0
          git push